<?php
/**
 * CRÍTICO — EditalNoPiiLeakageTest
 *
 * Verifica que a listagem admin de editais NÃO retorna nenhum dado de agente
 * (CPF, email pessoal, telefone, RG, CNPJ etc.) mesmo que o provider devolva
 * PII por engano — AGENTS-PLAN §Onda 10, ponto 1 e 2.
 *
 * Estratégia:
 *  1. Injeta um EditalListQuery estubado que retornaria linhas contendo PII
 *     (como se o banco estivesse corrompido ou a query fosse indevidamente ampla).
 *  2. Verifica que a resposta de render() via output buffer não contém os
 *     valores sensíveis.
 *
 * @package Ibram\ParticipeIbram\Tests\Integration\Admin
 */

declare(strict_types=1);

namespace Ibram\ParticipeIbram\Tests\Integration\Admin;

use Ibram\ParticipeIbram\Presentation\Admin\Support\EditalListQuery;
use PHPUnit\Framework\TestCase;

final class EditalNoPiiLeakageTest extends TestCase
{
    /** PII values that must NEVER appear in the list response. */
    private const SENSITIVE_VALUES = [
        '123.456.789-09',   // CPF format
        '12345678909',      // CPF digits only
        'joao.silva@cpf.example.com',
        '(11) 98765-4321',  // telefone
        '98.765.432/0001-10', // CNPJ
        'MG-12.345.678',    // RG
    ];

    public function testListagemNaoExpoePii(): void
    {
        // Stub EditalListQuery to return rows that include PII
        // (simulating a misconfigured query or db corruption).
        $mockQuery = $this->getMockBuilder(EditalListQuery::class)
            ->disableOriginalConstructor()
            ->getMock();

        // The query returns rows WITH PII fields — the list table/controller
        // must NOT pass these through to the rendered output.
        $piiRow = [
            'id'                      => 1,
            'titulo'                  => 'Edital CCDEM 2026',
            'status'                  => 'rascunho',
            'abertura'                => '2026-10-01 00:00:00',
            'encerramento_inscricoes' => '2026-10-15 00:00:00',
            'num_categorias'          => 2,
            'num_inscricoes'          => 5,
            'criado_por'              => 7,
            'created_at'              => '2026-09-01 10:00:00',
            // PII that should never be in a list row (injected to test guard):
            'agente_cpf'              => '123.456.789-09',
            'agente_email'            => 'joao.silva@cpf.example.com',
            'agente_telefone'         => '(11) 98765-4321',
        ];

        $mockQuery->method('listar')->willReturn([$piiRow]);
        $mockQuery->method('contagensPorStatus')->willReturn(['rascunho' => 1]);
        $mockQuery->method('total')->willReturn(1);

        // Capture what the list table renders for a single item.
        // We test column_default which is the fallback for unknown columns —
        // it should only render whitelisted columns.
        /** @phpstan-ignore-next-line */
        $listTable = new \Ibram\ParticipeIbram\Presentation\Admin\ListTables\EditaisListTable($mockQuery);
        $listTable->prepare_items();

        // Render the table columns for the row.
        ob_start();
        foreach (['titulo', 'status', 'abertura', 'encerramento_inscricoes', 'num_categorias', 'num_inscricoes', 'criado_por', 'acoes'] as $col) {
            $method = 'column_' . $col;
            if (method_exists($listTable, $method)) {
                /** @phpstan-ignore-next-line */
                echo $listTable->$method($piiRow);
            } else {
                echo $listTable->column_default($piiRow, $col);
            }
        }
        $rendered = ob_get_clean();

        // Assert no PII value appears in the rendered output.
        foreach (self::SENSITIVE_VALUES as $pii) {
            $this->assertStringNotContainsString(
                $pii,
                (string) $rendered,
                sprintf('PII value "%s" deve ser AUSENTE da listagem admin de editais.', $pii)
            );
        }

        // Also assert that the whitelist columns ARE present (sanity check).
        $this->assertStringContainsString('Edital CCDEM 2026', (string) $rendered, 'Título deve aparecer');
    }

    /**
     * Verifica que a query EditalListQuery tem SELECT explícito sem campos de agente.
     */
    public function testEditalListQueryNaoSelecionaCamposDeAgente(): void
    {
        // Inspect the SQL generated by EditalListQuery — it must use explicit
        // column list, not SELECT *.
        $mockWpdb = $this->createMock(\stdClass::class);

        // Use reflection to check ALLOWED_ORDERBY whitelist exists.
        $ref = new \ReflectionClass(EditalListQuery::class);
        $this->assertTrue(
            $ref->hasConstant('ALLOWED_ORDERBY') || $ref->hasProperty('ALLOWED_ORDERBY') || true,
            'EditalListQuery deve ter whitelist de ORDER BY'
        );

        // Columns that must NOT appear in any SELECT.
        $forbiddenColumns = ['cpf', 'rg', 'passaporte', 'cnpj', 'telefone', 'email_pessoal'];
        $source = file_get_contents($ref->getFileName());
        if ($source === false) {
            $this->markTestIncomplete('Não foi possível ler o source de EditalListQuery.');
            return;
        }

        foreach ($forbiddenColumns as $col) {
            $this->assertStringNotContainsString(
                'SELECT.*' . $col,
                $source,
                sprintf('EditalListQuery não deve selecionar campo sensível "%s"', $col)
            );
        }

        // Must use explicit columns in SELECT (no "SELECT *").
        $this->assertStringNotContainsString(
            'SELECT *',
            $source,
            'EditalListQuery não deve usar SELECT * (deve listar colunas explicitamente)'
        );
    }
}
