<?php
/**
 * Storage privado autenticado para documentos sensíveis (TD-09, TD-18).
 *
 * @package Ibram\ParticipeIbram\Infrastructure\Storage
 */

declare(strict_types=1);

namespace Ibram\ParticipeIbram\Infrastructure\Storage;

use Ibram\ParticipeIbram\Core\Audit\AuditLogger;
use Ibram\ParticipeIbram\Core\Helpers\UuidGenerator;

/**
 * Armazena anexos fora da raiz pública do WordPress.
 *
 * Layout em disco:
 *   {base}/                                       <- WP_CONTENT_DIR/uploads/participe-ibram-private
 *   {base}/.htaccess                              <- Deny from all (Apache)
 *   {base}/web.config                             <- deny users="*" (IIS)
 *   {base}/index.php                              <- silence file
 *   {base}/{YYYY}/{MM}/{owner}/{uuid}.{ext}       <- arquivo final
 *
 * Garantias:
 *  - MIME real é detectado por `finfo_file()` (R5 V-15) — extensão é descartada.
 *  - Path traversal é bloqueado em todo método público (compara `realpath()`
 *    canonicalizado com o `realpath()` do diretório base).
 *  - Acesso a leitura/download é AUDITADO via AuditLogger ({@see TD-14}).
 */
final class PrivateFileStorage
{
    /**
     * Subpasta dentro de WP_CONTENT_DIR/uploads.
     */
    public const BASE_SUBDIR = 'participe-ibram-private';

    /**
     * Mapa MIME -> extensão preferencial.
     *
     * Extensões NÃO vêm do nome original — são derivadas do MIME real.
     */
    private const MIME_TO_EXT = [
        'application/pdf' => 'pdf',
        'image/jpeg'      => 'jpg',
        'image/jpg'       => 'jpg',
        'image/png'       => 'png',
        'image/gif'       => 'gif',
        'image/webp'      => 'webp',
        'image/heic'      => 'heic',
        'text/plain'      => 'txt',
    ];

    /**
     * .htaccess template — Apache 2.2 e 2.4 friendly.
     */
    private const HTACCESS = <<<HT
# Generated by participe-ibram. Do not edit.
Order deny,allow
Deny from all
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>

HT;

    /**
     * web.config para IIS.
     */
    private const WEBCONFIG = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <authorization>
      <deny users="*"/>
    </authorization>
  </system.webServer>
</configuration>
XML;

    /**
     * Conteúdo do `index.php` em cada subpasta.
     */
    private const INDEX_PHP = "<?php\n// Silence is golden.\n";

    /**
     * Caminho absoluto do diretório base (sem trailing slash). Resolvido no
     * construtor.
     */
    private string $baseDir;

    /**
     * Caminho absoluto canonicalizado do diretório base — alvo de comparações
     * de prevenção a path traversal.
     */
    private string $baseDirReal;

    private AuditLogger $auditLogger;

    /**
     * @param AuditLogger $auditLogger Logger de auditoria (TD-14).
     * @param string|null $baseDir     Override (testes); default usa WP_CONTENT_DIR.
     *
     * @throws StorageException Quando não é possível preparar o diretório.
     */
    public function __construct(AuditLogger $auditLogger, ?string $baseDir = null)
    {
        $this->auditLogger = $auditLogger;
        $this->baseDir     = self::resolveBaseDir($baseDir);
        $this->ensureBaseDir();
        $real = realpath($this->baseDir);
        if ($real === false) {
            throw StorageException::dirCreationFailed($this->baseDir);
        }
        $this->baseDirReal = self::normaliseSeparators($real);
    }

    /**
     * Diretório base (caminho canônico).
     */
    public function baseDir(): string
    {
        return $this->baseDirReal;
    }

    /**
     * Armazena um arquivo recém-uploaded (PHP tmp ou caminho qualquer legível).
     *
     * Operações realizadas:
     *  1. Valida que o arquivo existe e é legível.
     *  2. Detecta MIME real via `finfo_file` (R5 V-15).
     *  3. Calcula SHA-256 do conteúdo.
     *  4. Sanitiza o nome original (`sanitize_file_name`) — apenas para o
     *     metadado; o nome em disco usa UUID + extensão derivada do MIME real.
     *  5. Move/copia o tmp para `{base}/{YYYY}/{MM}/{ownerKey}/{uuid}.{ext}`.
     *
     * @param string $tmpPath      Caminho do arquivo tmp/uploaded.
     * @param string $originalName Nome original do upload.
     * @param int    $agenteId     ID do agente dono. Use 0 quando ainda não
     *                             houver agente; nesse caso o storage usa um
     *                             hash anônimo derivado do tmp.
     *
     * @return array{path:string,hash:string,mime:string,size:int} Metadados; `path` é relativo a `baseDir`.
     *
     * @throws StorageException
     */
    public function store(string $tmpPath, string $originalName, int $agenteId): array
    {
        if (!is_file($tmpPath) || !is_readable($tmpPath)) {
            throw StorageException::fileNotReadable();
        }

        $size = filesize($tmpPath);
        if ($size === false || $size < 0) {
            throw StorageException::fileNotReadable();
        }

        $mime = self::detectMime($tmpPath);
        $hash = hash_file('sha256', $tmpPath);
        if (!is_string($hash) || $hash === '') {
            throw StorageException::fileNotReadable();
        }

        $ext = self::extensionForMime($mime);

        // Sanitiza o nome original (apenas para registro em DB, não usado em disco).
        // Mantemos a chamada para detectar erros precoces.
        if (function_exists('sanitize_file_name')) {
            sanitize_file_name($originalName);
        }

        $year     = gmdate('Y');
        $month    = gmdate('m');
        $ownerKey = $agenteId > 0
            ? (string) $agenteId
            : 'anon-' . substr(hash('sha256', $hash . '|' . $tmpPath), 0, 16);

        $relativeDir = $year . '/' . $month . '/' . $ownerKey;
        $absoluteDir = $this->baseDirReal . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relativeDir);
        $this->ensureSubDir($absoluteDir);

        $filename     = UuidGenerator::generate() . '.' . $ext;
        $relativePath = $relativeDir . '/' . $filename;
        $absolutePath = $absoluteDir . DIRECTORY_SEPARATOR . $filename;

        // Path traversal guard: o caminho final deve continuar sob baseDirReal.
        $this->assertWithinBase($absolutePath, /*allowMissing*/ true);

        // Move se for upload PHP, senão copia.
        $moved = false;
        if (function_exists('is_uploaded_file') && is_uploaded_file($tmpPath)) {
            $moved = function_exists('move_uploaded_file')
                ? @move_uploaded_file($tmpPath, $absolutePath)
                : false;
        }
        if (!$moved) {
            $moved = @copy($tmpPath, $absolutePath);
        }
        if (!$moved) {
            throw StorageException::fileNotWritable();
        }

        @chmod($absolutePath, 0640);

        return [
            'path' => $relativePath,
            'hash' => $hash,
            'mime' => $mime,
            'size' => (int) $size,
        ];
    }

    /**
     * Lê o conteúdo de um arquivo (auditado).
     *
     * @param string $relativePath Caminho relativo ao baseDir.
     * @param int    $atorId       WP user id que fez o request.
     *
     * @throws StorageException
     */
    public function read(string $relativePath, int $atorId): string
    {
        $absolute = $this->resolveSafe($relativePath);
        $contents = @file_get_contents($absolute);
        if ($contents === false) {
            throw StorageException::fileNotReadable();
        }

        $this->auditLogger->log(
            'documento_arquivo',
            null,
            'ler_arquivo',
            null,
            ['path' => $relativePath, 'bytes' => strlen($contents)],
            $atorId > 0 ? $atorId : null
        );

        return $contents;
    }

    /**
     * Faz stream do arquivo para o browser e finaliza a request.
     *
     * Audita o acesso antes de enviar bytes (TD-14). Em caso de erro de I/O,
     * lança StorageException sem enviar headers.
     *
     * @param string $relativePath
     * @param string $originalName Nome a ser oferecido no `Content-Disposition`.
     * @param int    $atorId
     *
     * @throws StorageException
     */
    public function streamDownload(string $relativePath, string $originalName, int $atorId): void
    {
        $absolute = $this->resolveSafe($relativePath);
        $size     = @filesize($absolute);
        if ($size === false) {
            throw StorageException::fileNotReadable();
        }
        $mime = self::detectMime($absolute);

        $this->auditLogger->log(
            'documento_arquivo',
            null,
            'download_arquivo',
            null,
            ['path' => $relativePath, 'bytes' => $size, 'mime' => $mime],
            $atorId > 0 ? $atorId : null
        );

        $safeName = self::sanitizeDownloadName($originalName);

        // Headers (idempotentes — exigidos para downloads autenticados).
        if (!headers_sent()) {
            header('Content-Type: ' . $mime);
            header('Content-Length: ' . (string) $size);
            header('Content-Disposition: attachment; filename="' . $safeName . '"');
            header('Cache-Control: private, no-store, max-age=0');
            header('X-Content-Type-Options: nosniff');
            header('Pragma: no-cache');
        }

        // Limpa buffers para não estourar memória em arquivos grandes.
        while (ob_get_level() > 0) {
            @ob_end_clean();
        }

        $bytes = @readfile($absolute);
        if ($bytes === false) {
            throw StorageException::fileNotReadable();
        }
        // Encerra a request — caller espera comportamento "send & exit".
        if (function_exists('wp_die')) {
            // wp_die em ajax exit mais limpo, mas em download cru exit é seguro.
            exit;
        }
        exit; // @codeCoverageIgnore
    }

    /**
     * Remove o arquivo. Idempotente: arquivo ausente retorna false sem lançar.
     *
     * @throws StorageException Se o path violar o base dir.
     */
    public function delete(string $relativePath): bool
    {
        $absolute = $this->resolveSafe($relativePath, /*allowMissing*/ true);
        if (!file_exists($absolute)) {
            return false;
        }
        $ok = @unlink($absolute);
        if (!$ok) {
            throw StorageException::deleteFailed();
        }

        return true;
    }

    /* ---------------------------------------------------------------------
     * Internals
     * ------------------------------------------------------------------- */

    /**
     * Determina o caminho base efetivo.
     */
    private static function resolveBaseDir(?string $override): string
    {
        if ($override !== null && $override !== '') {
            return rtrim($override, "/\\");
        }
        $contentDir = defined('WP_CONTENT_DIR')
            ? (string) WP_CONTENT_DIR
            : sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'wp-content';

        return rtrim($contentDir, "/\\")
            . DIRECTORY_SEPARATOR . 'uploads'
            . DIRECTORY_SEPARATOR . self::BASE_SUBDIR;
    }

    /**
     * Cria o diretório base e os arquivos de proteção (htaccess/webconfig/index).
     */
    private function ensureBaseDir(): void
    {
        if (!is_dir($this->baseDir)) {
            $created = function_exists('wp_mkdir_p')
                ? \wp_mkdir_p($this->baseDir)
                : @mkdir($this->baseDir, 0750, true);
            if (!$created && !is_dir($this->baseDir)) {
                throw StorageException::dirCreationFailed($this->baseDir);
            }
        }

        $htaccess = $this->baseDir . DIRECTORY_SEPARATOR . '.htaccess';
        if (!file_exists($htaccess)) {
            @file_put_contents($htaccess, self::HTACCESS);
        }
        $webconfig = $this->baseDir . DIRECTORY_SEPARATOR . 'web.config';
        if (!file_exists($webconfig)) {
            @file_put_contents($webconfig, self::WEBCONFIG);
        }
        $indexPhp = $this->baseDir . DIRECTORY_SEPARATOR . 'index.php';
        if (!file_exists($indexPhp)) {
            @file_put_contents($indexPhp, self::INDEX_PHP);
        }
    }

    /**
     * Cria subpastas (com index.php em cada nível) garantindo que TODAS estão
     * dentro do base dir.
     */
    private function ensureSubDir(string $absoluteDir): void
    {
        // Resolvemos o pai existente para evitar criar diretório fora do base.
        // Caminhamos do baseDir adicionando segmentos um a um.
        $rel = substr($absoluteDir, strlen($this->baseDirReal));
        $rel = ltrim((string) $rel, "/\\");
        if ($rel === '') {
            return;
        }

        $segments = preg_split('#[\\\\/]+#', $rel) ?: [];
        $current  = $this->baseDirReal;
        foreach ($segments as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..') {
                throw StorageException::pathTraversalDetected();
            }
            $current .= DIRECTORY_SEPARATOR . $segment;
            if (!is_dir($current)) {
                $created = function_exists('wp_mkdir_p')
                    ? \wp_mkdir_p($current)
                    : @mkdir($current, 0750, true);
                if (!$created && !is_dir($current)) {
                    throw StorageException::dirCreationFailed($current);
                }
            }
            $indexPhp = $current . DIRECTORY_SEPARATOR . 'index.php';
            if (!file_exists($indexPhp)) {
                @file_put_contents($indexPhp, self::INDEX_PHP);
            }
        }
    }

    /**
     * Resolve um path relativo para absoluto e valida que está dentro do base.
     *
     * @param string $relativePath
     * @param bool   $allowMissing Se true, aceita arquivo inexistente (delete/store).
     */
    private function resolveSafe(string $relativePath, bool $allowMissing = false): string
    {
        $rel = trim($relativePath);
        if ($rel === '' || $rel[0] === '/' || $rel[0] === '\\' || strpos($rel, '..') !== false) {
            throw StorageException::pathTraversalDetected();
        }

        // Normaliza separadores e impede absolute paths (Windows).
        if (preg_match('/^[a-zA-Z]:/', $rel) === 1) {
            throw StorageException::pathTraversalDetected();
        }
        $rel       = str_replace('/', DIRECTORY_SEPARATOR, $rel);
        $candidate = $this->baseDirReal . DIRECTORY_SEPARATOR . $rel;

        return $this->assertWithinBase($candidate, $allowMissing);
    }

    /**
     * Garante que `$candidate` esteja sob `$this->baseDirReal` mesmo após
     * resolução de symlinks (`realpath`).
     *
     * Se o arquivo ainda não existe (caso de `store`), valida o diretório pai.
     *
     * @return string Caminho canônico.
     */
    private function assertWithinBase(string $candidate, bool $allowMissing): string
    {
        $real = realpath($candidate);
        if ($real === false) {
            if (!$allowMissing) {
                throw StorageException::fileNotReadable();
            }
            $parent = dirname($candidate);
            $parentReal = realpath($parent);
            if ($parentReal === false) {
                throw StorageException::pathTraversalDetected();
            }
            $parentReal = self::normaliseSeparators($parentReal);
            if (!self::isUnder($parentReal, $this->baseDirReal)) {
                throw StorageException::notInBaseDir();
            }
            return $parentReal . DIRECTORY_SEPARATOR . basename($candidate);
        }
        $real = self::normaliseSeparators($real);
        if (!self::isUnder($real, $this->baseDirReal)) {
            throw StorageException::notInBaseDir();
        }

        return $real;
    }

    /**
     * Detecta MIME real via finfo (R5 V-15).
     */
    private static function detectMime(string $absolutePath): string
    {
        if (!function_exists('finfo_open')) {
            // Fallback razoável: PHP sem ext-fileinfo. Em produção isto não
            // deve ocorrer; lançamos para o caller decidir.
            throw StorageException::fileNotReadable();
        }
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        if ($finfo === false) {
            throw StorageException::fileNotReadable();
        }
        try {
            $mime = finfo_file($finfo, $absolutePath);
        } finally {
            finfo_close($finfo);
        }
        if (!is_string($mime) || $mime === '') {
            throw StorageException::fileNotReadable();
        }

        return strtolower($mime);
    }

    /**
     * Mapeia MIME para extensão. Default: `bin`.
     */
    private static function extensionForMime(string $mime): string
    {
        $key = strtolower($mime);

        return self::MIME_TO_EXT[$key] ?? 'bin';
    }

    /**
     * Sanitiza um nome para uso em `Content-Disposition`. Evita CRLF / "
     */
    private static function sanitizeDownloadName(string $name): string
    {
        if (function_exists('sanitize_file_name')) {
            $name = (string) \sanitize_file_name($name);
        }
        $name = preg_replace('/[\r\n"\\\\]+/', '_', $name) ?? 'arquivo';
        if ($name === '') {
            $name = 'arquivo';
        }

        return substr($name, 0, 200);
    }

    /**
     * Verifica se `$child` está sob `$parent` (ambos canônicos).
     */
    private static function isUnder(string $child, string $parent): bool
    {
        $parent = rtrim($parent, "/\\") . DIRECTORY_SEPARATOR;
        $child  = rtrim($child, "/\\") . DIRECTORY_SEPARATOR;

        return strncmp($child, $parent, strlen($parent)) === 0;
    }

    /**
     * Normaliza separadores para o SO atual (Windows usa `\`).
     */
    private static function normaliseSeparators(string $path): string
    {
        return str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $path);
    }
}
